# Generated by Django 3.2 on 2022-04-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Checkout',
        ),
    ]
